name: Jarvis Dining Notifier

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: |
          curl -d "GitHub Actions is working!" -H "Title: Jarvis Test" https://ntfy.sh/jarvis-patrick
